spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bughua_blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.lrm: info
  file: log/blog-pro.log

server:
  port: 443
  ssl:
    key-store: 2456072_www.bughua.com.pfx
    key-store-password: inN6Lq0e
